USE Hackathon;

DELETE FROM Municipio;

INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (13,'AGUADA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (20,'ALBANIA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (20,'ALBANIA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (51,'ARATOCA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (51,'ARATOCA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (77,'BARBOSA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (77,'BARBOSA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (79,'BARICHARA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (79,'BARICHARA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (92,'BETULIA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (92,'BETULIA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (101,'BOLÍVAR','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (101,'BOLÍVAR','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (121,'CABRERA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (132,'CALIFORNIA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (147,'CAPITANEJO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (152,'CARCASÍ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (160,'CEPITÁ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (160,'CEPITÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (162,'CERRITO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (162,'CERRITO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (167,'CHARALÁ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (167,'CHARALÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (169,'CHARTA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (169,'CHARTA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (176,'CHIMA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (176,'CHIMA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (179,'CHIPATÁ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (179,'CHIPATÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (190,'CIMITARRA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (190,'CIMITARRA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (207,'CONCEPCIÓN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (207,'CONCEPCIÓN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (209,'CONFINES','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (209,'CONFINES','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (211,'CONTRATACIÓN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (211,'CONTRATACIÓN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (217,'COROMORO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (217,'COROMORO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (229,'CURITÍ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (229,'CURITÍ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (235,'EL CARMEN DE CHUCURÍ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (235,'EL CARMEN DE CHUCURÍ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (245,'EL GUACAMAYO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (245,'EL GUACAMAYO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (250,'EL PEÑÓN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (250,'EL PEÑÓN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (255,'EL PLAYÓN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (255,'EL PLAYÓN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (264,'ENCINO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (266,'ENCISO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (266,'ENCISO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (271,'FLORIÁN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (271,'FLORIÁN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (296,'GALÁN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (296,'GALÁN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (298,'GAMBITA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (298,'GAMBITA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (320,'GUADALUPE','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (320,'GUADALUPE','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (322,'GUAPOTÁ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (322,'GUAPOTÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (324,'GUAVATÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (327,'GÜEPSA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (344,'HATO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (344,'HATO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (368,'JESÚS MARÍA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (368,'JESÚS MARÍA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (370,'JORDÁN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (377,'LA BELLEZA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (377,'LA BELLEZA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (385,'LANDÁZURI','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (385,'LANDÁZURI','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (397,'LA PAZ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (406,'LEBRÍJA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (406,'LEBRÍJA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (418,'LOS SANTOS','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (418,'LOS SANTOS','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (425,'MACARAVITA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (425,'MACARAVITA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (432,'MÁLAGA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (432,'MÁLAGA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (444,'MATANZA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (444,'MATANZA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (464,'MOGOTES','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (464,'MOGOTES','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (468,'MOLAGAVITA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (498,'OCAMONTE','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (498,'OCAMONTE','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (500,'OIBA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (500,'OIBA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (502,'ONZAGA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (522,'PALMAR','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (522,'PALMAR','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (524,'PALMAS DEL SOCORRO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (524,'PALMAS DEL SOCORRO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (533,'PÁRAMO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (533,'PÁRAMO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (549,'PINCHOTE','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (549,'PINCHOTE','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (572,'PUENTE NACIONAL','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (572,'PUENTE NACIONAL','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (573,'PUERTO PARRA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (573,'PUERTO PARRA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (575,'PUERTO WILCHES','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (575,'PUERTO WILCHES','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (615,'RIONEGRO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (615,'RIONEGRO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (655,'SABANA DE TORRES','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (655,'SABANA DE TORRES','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (669,'SAN ANDRÉS','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (669,'SAN ANDRÉS','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (673,'SAN BENITO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (673,'SAN BENITO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (679,'SAN GIL','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (679,'SAN GIL','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (682,'SAN JOAQUÍN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (684,'SAN JOSÉ DE MIRANDA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (689,'SAN VICENTE DE CHUCURÍ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (689,'SAN VICENTE DE CHUCURÍ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (705,'SANTA BÁRBARA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (705,'SANTA BÁRBARA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (720,'SANTA HELENA DEL OPÓN','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (720,'SANTA HELENA DEL OPÓN','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (745,'SIMACOTA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (745,'SIMACOTA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (755,'SOCORRO','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (755,'SOCORRO','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (770,'SUAITA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (773,'SUCRE','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (773,'SUCRE','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (780,'SURATÁ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (780,'SURATÁ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (820,'TONA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (820,'TONA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (855,'VALLE DE SAN JOSÉ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (855,'VALLE DE SAN JOSÉ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (861,'VÉLEZ','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (861,'VÉLEZ','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (867,'VETAS','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (872,'VILLANUEVA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (872,'VILLANUEVA','RURAL');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (895,'ZAPATOCA','URBANA');
INSERT INTO Municipio (Mun_Num, Mun_Nombre, Mun_RU) VALUES (895,'ZAPATOCA','RURAL');
