//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace enDemanda.AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persona
    {
        public int Per_Id { get; set; }
        public string Per_Gen { get; set; }
        public int Per_Edad { get; set; }
        public int Per_Grado { get; set; }
        public string Per_Situ { get; set; }
        public string Per_Etnia { get; set; }
        public string Per_Discapacidad { get; set; }
        public int Per_Calif { get; set; }
        public bool Per_Cocina { get; set; }
        public bool Per_Pintura { get; set; }
        public bool Per_Aseo { get; set; }
        public bool Per_Ropa { get; set; }
        public bool Per_Jardineria { get; set; }
        public Nullable<int> Per_NumMun { get; set; }
        public string Per_Correo { get; set; }
    
        public virtual Municipio Municipio { get; set; }
    }
}
